### ISSUE TITLE
Non-typescript version?

### ISSUE THREAD

**Issue by rustinlewis** [erikvullings/mithril-tree-component#6]
Specs don't allow typescript for our project, any chance you have a compiled non-typescript version?

**Comment by erikvullings** [comment]
@rustinlewis sorry, but I've missed your issue completely, so hopefully you have already discovered the component on [npm](https://www.npmjs.com/package/mithril-tree-component). Alternatively, you can use it directly from [unpkg (as javascript module)](https://unpkg.com/mithril-tree-component) or [regular js](https://unpkg.com/mithril-tree-component@0.6.7/dist/mithril-tree-component.js).
